### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ashquarky** [QuarkTheAwesome/LiteNESU#1]
At this point, my two main priorities are speed and buglessness. List time!
- [x] Figure out what the heck is going on with Super Mario Bros. (blarg's tests came up with the below)
  - [ ] Don't buffer the palette like other VRAM
  - [ ] Dont change the read buffer by other VRAM writes
- [ ] Rewrite in GX2 (The OSScreen methods take their sweet time.)
- [ ] Have the home button actually exit, not crash the system
- [ ] General speedup (if possible)
- [ ] Get someone to tell me how this Makefile works so I can have more source files than just init and loader

Hmm. Looks like I have low expectations of what needs to be done ;3

**Comment by ashquarky** [comment]
Updated with what exactly is going wrong with the PPU.
